specVersion: "0.2.0"

name: "Subql-Starter"
version: "0.0.0"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: 'wss://gateway.testnet.octopus.network/atocha/yevqd2d4jhm0dqakaj4hkbyjjfg6ukbu'
  genesisHash: '0x1a0aadf6b8c9cee2789c8141e50340ceaccce41dc101569dbea8d8ca9dd8b856' # Atocha - OTC - TestNet

dataSources:
  - kind: substrate/Runtime
#    startBlock: 63000
#    startBlock: 129700
#    startBlock: 201200
    startBlock: 89800
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePuzzleCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: PuzzleCreated
        - handler: handleAnswerCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: AnswerCreated
        - handler: handleChallengeDepositEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: ChallengeDeposit
        - handler: handleChallengeStatusChangeEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: ChallengeStatusChange
        - handler: handlePuzzleStatusChangeEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: PuzzleStatusChange
        - handler: handleTakeTokenRewardEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: TakeTokenReward
        - handler: handleTakePointRewardEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: TakePointReward
        - handler: handlePuzzleDepositEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: PuzzleDeposit
        - handler: handleAnnouncePuzzleChallengeDeadlineEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: AnnouncePuzzleChallengeDeadline
        - handler: handleChallengeRaisePeriodDeadlineEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: ChallengeRaisePeriodDeadline

