specVersion: "0.2.0"

name: "Subql-Starter"
version: "0.0.0"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: 'ws://148.72.247.143:8844'
  genesisHash: '0x9ec6cc59bfc137abf5aca3cb958e2add2815e0cde715e2c3081b7183219acd2a' # Atocha

dataSources:
  - kind: substrate/Runtime
    startBlock: 114800
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePuzzleCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: PuzzleCreated
        - handler: handleAnswerCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: AnswerCreated
        - handler: handleChallengeDepositEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinace
            method: ChallengeDeposit
        - handler: handleChallengeStatusChangeEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinace
            method: ChallengeStatusChange

