specVersion: "0.2.0"

name: "Subql-Starter"
version: "0.0.0"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: 'wss://gateway.mainnet.octopus.network/atocha/jungxomf4hdcfocwcalgoiz64g9avjim'
  genesisHash: '0x1f11f745be512a17f39b571a9391b5ee6747b900c1db98176828e4a1346dbe9b' # Atocha - OTC - Mainnet

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePuzzleCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: PuzzleCreated
        - handler: handleAnswerCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: AnswerCreated
        - handler: handleChallengeDepositEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: ChallengeDeposit
        - handler: handleChallengeStatusChangeEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: ChallengeStatusChange
        - handler: handlePuzzleStatusChangeEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: PuzzleStatusChange
        - handler: handleTakeTokenRewardEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: TakeTokenReward
        - handler: handleTakePointRewardEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: TakePointReward
        - handler: handlePuzzleDepositEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: PuzzleDeposit
        - handler: handleAnnouncePuzzleChallengeDeadlineEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: AnnouncePuzzleChallengeDeadline
        - handler: handleChallengeRaisePeriodDeadlineEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinance
            method: ChallengeRaisePeriodDeadline

