specVersion: "0.2.0"

name: "Subql-Starter"
version: "0.0.0"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: 'ws://148.72.247.143:8844'
  genesisHash: '0x17264823cc020f0f009cfef5e75b6c5d8cb020ef18e2d62ff613db6cfe46d806' # Atocha

dataSources:
  - kind: substrate/Runtime
#    startBlock: 63000
    startBlock: 92000
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handlePuzzleCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: PuzzleCreated
        - handler: handleAnswerCreatedEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: AnswerCreated
        - handler: handleChallengeDepositEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinace
            method: ChallengeDeposit
        - handler: handleChallengeStatusChangeEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinace
            method: ChallengeStatusChange
        - handler: handlePuzzleStatusChangeEvent
          kind: substrate/EventHandler
          filter:
            module: atochaModule
            method: PuzzleStatusChange
        - handler: handleTakeTokenRewardEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinace
            method: TakeTokenReward
        - handler: handleTakePointRewardEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinace
            method: TakePointReward
        - handler: handlePuzzleDepositEvent
          kind: substrate/EventHandler
          filter:
            module: atochaFinace
            method: PuzzleDeposit